apiVersion: celeryproject.org/v1alpha1
kind: Celery
metadata:
  name: example-celery-obj
spec:
  image: example-image
  imagePullPolicy: Never
  appName: example
  celeryApp: 'app:celery_app'
  celeryVersion: "5.0"
  workerReplicas: 3
  flowerReplicas: 2
  workerSpec:
    args: [ "--loglevel", "INFO", "-Ofair", "-Q", "celery", "-c", "2" ]
    resources:
      requests:
        cpu: "100m"
        memory: "64Mi"
      limits:
        cpu: "200m"
        memory: "128Mi"
  flowerSpec:
    service:
      metadata:
        name: celery-example-flower
        namespace: default
        labels:
          app: celery-example-flower
      spec:
        type: NodePort
        ports:
        - port: 5555
          protocol: TCP
        selector:
          run: celery-example-flower
    resources:
      requests:
        cpu: "100m"
        memory: "64Mi"
      limits:
        cpu: "200m"
        memory: "128Mi"