apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: celery-operator
  name: celery-operator
  namespace: default
spec:
  minReadySeconds: 5
  progressDeadlineSeconds: 600
  replicas: 1
  selector:
    matchLabels:
      app: celery-operator
  strategy:
    rollingUpdate:
      maxSurge: 20%
      maxUnavailable: 0%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: celery-operator
    spec:
      serviceAccountName: celery-account
      containers:
      - name: celery-operator
        image: celery-operator
        imagePullPolicy: Never
        resources:
          requests:
            cpu: "100m"
            memory: "64Mi"
          limits:
            cpu: "200m"
            memory: "128Mi"